packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Core
  next: ^14.2.35
  lucide-react: ^0.487.0
  axios: ^1.8.4

  # Styling
  tailwindcss: ^3.4.13
  autoprefixer: ^10
  postcss: ^8

  # Linting & Formatting
  eslint: ^8.57.0
  prettier: ^3.3.3

  # TypeScript
  typescript: ^5.6.3
  "@types/node": ^20
  "@types/eslint": ^8

  # Analytics
  "@vercel/analytics": ^1.5.0

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.0
